#ifndef MKS57D_INTERRUPT_PRIORITY_H
#define MKS57D_INTERRUPT_PRIORITY_H

#include <stdbool.h>

enum
{
    INTERRUPT_PRIORITY_GROUP_ALL_PREEMPT = 3u,
    INTERRUPT_PRIORITY_EMERGENCY_FAULT = 0u,
    INTERRUPT_PRIORITY_CONTROL_GUARDIAN = 1u,
    INTERRUPT_PRIORITY_FAST_CURRENT = 2u,
    INTERRUPT_PRIORITY_ROTOR_FEEDBACK = 4u,
    INTERRUPT_PRIORITY_MOTION_CAPTURE = 6u,
    INTERRUPT_PRIORITY_COMMUNICATIONS = 8u,
    INTERRUPT_PRIORITY_SLOW_RELEASE = 12u,
    INTERRUPT_PRIORITY_TIMEKEEPING = 15u
};

bool interrupt_priority_init(void);

#endif
