#ifndef MKS57D_SPI_STATUS_H
#define MKS57D_SPI_STATUS_H

typedef enum
{
    SPI_STATUS_OK = 0,
    SPI_STATUS_INVALID_ARGUMENT,
    SPI_STATUS_NOT_READY,
    SPI_STATUS_BUS_BUSY,
    SPI_STATUS_TRANSMIT_TIMEOUT,
    SPI_STATUS_RECEIVE_TIMEOUT,
    SPI_STATUS_COMPLETE_TIMEOUT,
    SPI_STATUS_PERIPHERAL_ERROR
} spi_status_t;

#endif
